### ISSUE TITLE
From pycrpto to pycryptodome ?

### ISSUE THREAD

**Issue by ovarene** [FFM/pycryptopan#7]
at the library dependance level, 
would it be interesting to move from
* pycrypto 
no more maintained - last version from Oct 2013
no more web sites
https://pypi.org/project/pycrypto/#history
to 
* pycryptodome
maintained - last version from August 2019
https://pypi.org/project/pycryptodome/#history

?

if you are interrested, I can perform the migration.

Regards

**Comment by ovarene** [comment]
I performed the work but
* with pycrypto
10000 anonymizations in 1.0221068859100342 s
rate: 9783.712582 anonymizations /sec

* with pycryptodome
10000 anonymizations in 1.8363702297210693 s
rate: 5445.525003 anonymizations /sec

is it worth it ?

**Comment by aaronkaplan** [comment]
Dear @ovarene , first of all thanks a lot for all your efforts! I *really* appreciate it.
It's very cool to have someone else interested in this little library. 

Concerning the speed: hm... not worth it probably.
However, we might look at this library and call it via cffi or similar:
https://en.wikipedia.org/wiki/Crypto-PAn#cite_note-Stott-4
(David Stott) made a *really* fast implementation in C++ which utilizes the AES-NI instruction AFAIK.
I still have it lying around somewhere and we could resurrect it and make it accessible via python.

So if there is interest in a really fast python implementation, I could dig up that old code, make a testing branch and I would be curious to hear what you think.

**Comment by aaronkaplan** [comment]
Dear @ovarene ,

I checked out some old slides which I made for my company which has a comparison of the speed (on my server) for the different cryptoPan libs:


# (Incomplete) Overview of CryptoPan implementations

Name | Speed | Language | URL
-- | -- | -- | --
Pycryptopan | 4k ops/sec | Python | https://github.com/FFM/pycryptopan
YaCryptopan | 2k ops/sec | Python | https://github.com/keiichishima/yacryptopan/
John Kristof’s implementation | ? | Perl | https://metacpan.org/pod/IP::Anonymous
C++ original implemtentation by   Jinliang Fan | ? | C++ | https://www.cc.gatech.edu/computing/Telecomm/projects/cryptopan/
David Stott (Lucent) C++ implementation   with AES-NI | 300 k ops/sec | C++ | https://www.cc.gatech.edu/computing/Networking/projects/cryptopan/lucent.shtml
OpenCores implementation | ? | Hardware language | ?

**Comment by ovarene** [comment]
Indeed David Stott's implementation seems pretty darn fast 👍

however, the link to the C++ source code seems dead.

**Comment by aaronkaplan** [comment]
Yup. As said, I still have a local copy. Could dig it up and (the license permitting) upload it here. Will check if it's doable.

**Comment by ovarene** [comment]
I was looking at it 👍
I'll have a look.
Thanks a lot
Regards

**Comment by aaronkaplan** [comment]
hey @ovarene , just wondering if you got it to work? And if so, are you happy with the performance?
best

**Comment by aaronkaplan** [comment]
hey @ovarene , if it's ok for you I will close this issue now in case no further input / request is coming from your side.

**Comment by ovarene** [comment]
Yes, that's fine with me
Thanks a lot


\-------- Message d'origine --------
On 15 oct. 2019 à 14:06, AaronK < notifications@github.com > a écrit :
hey @ovarene , if it's ok for you I will close this issue now in case no further input / request is coming from your side.
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.￼
\[ \{ "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": \{ "@type": "ViewAction", "target": "https://github.com/FFM/pycryptopan/issues/7?email\_source=notifications">https://github.com/FFM/pycryptopan/issues/7?email\_source=notifications\\u0026email\_token=AAO3U4LUFEGNUATEN62OX63QOWW4DA5CNFSM4IXENKVKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEBIP6AI\#issuecomment-542179073", "url": "https://github.com/FFM/pycryptopan/issues/7?email\_source=notifications">https://github.com/FFM/pycryptopan/issues/7?email\_source=notifications\\u0026email\_token=AAO3U4LUFEGNUATEN62OX63QOWW4DA5CNFSM4IXENKVKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEBIP6AI\#issuecomment-542179073", "name": "View Issue" \}, "description": "View this Issue on GitHub", "publisher": \{ "@type": "Organization", "name": "GitHub", "url": "https://github.com" \} \} \]

**Comment by aaronkaplan** [comment]
Thanks, closing. Hope the Lucent version (C++) worked for you and is running smoothly. If not, let me know.
